### ISSUE TITLE
Cannot dump map to pickle in create_map.py 

### ISSUE THREAD

**Issue by hengluchang** [gges5110/ATXHackTheTraffic#13]

**Comment by hengluchang** [comment]
fixed it by dumping adjacency list to pickle instead.

**Comment by gges5110** [comment]
When did we fix this? @hengluchang Do you know which PR?

**Comment by hengluchang** [comment]
@gges5110 We deployed the get_map_from_file() method in create_map.py offline, I am not sure which PR is that.

**Comment by gges5110** [comment]
I think [this](https://github.com/gges5110/ATXHackTheTraffic/blob/4d019a03ad7b0026b9b0eb7d7bbca5ae51556e0d/create_map.py) is when I fixed the code.
