### ISSUE TITLE
Overwriting the inputs.

### ISSUE THREAD

**Issue by gges5110** [gges5110/ATXHackTheTraffic#15]
You are taking input variables [here](https://github.com/gges5110/ATXHackTheTraffic/blob/f9fe9c935ddd3997896f88bc41174093b11512bf/tests/CorridorTravelTime.py#L11) but you overwrite them [here](https://github.com/gges5110/ATXHackTheTraffic/blob/f9fe9c935ddd3997896f88bc41174093b11512bf/tests/CorridorTravelTime.py#L49). Please comment out the part where you set the three variables or come up with other fixes.

**Comment by ernie7334066** [comment]
I already fix this issue in the corriodor branch that David and I are working on now. We will merge the corriodor branch with master after we're done. Thanks for checking though!
